### ISSUE TITLE
GPUs seems not runing when training

### ISSUE THREAD

**Issue by ShawnCao2023** [autonomousvision/tuplan_garage#13]
I encountered issues when running the tuplan-garage project on my computer. The training process on the nuplan dataset was slow and the GPU memory usage was only at 20%.  I tried on the A100 cluster, the GPU usage was pretty low too. 

I have been using the default training settings. I'm curious if any important settings were overlooked during the process?

[GPU_no_runing.txt](https://github.com/autonomousvision/tuplan_garage/files/12508984/GPU_no_runing.txt)

GPU usage info
![image](https://github.com/autonomousvision/tuplan_garage/assets/141105007/f413f0ce-84f7-402b-977f-25233843f252)

**Comment by DanielDauner** [comment]
Hi @ShawnCao2023. Given that most of our models are simple MLPs, the training should be relatively fast (~30 min), and the GPU memory workload is relatively low. 

Have you created the feature cache before running training? Otherwise, the training script will compute the features during the first epoch, which is exceptionally slow. As pointed out in the `advanced_model_training.ipynb` (see [here](https://github.com/motional/nuplan-devkit/blob/master/tutorials/nuplan_advanced_model_training.ipynb)), it's beneficial first to generate the cache with the arguments `py_func=cache` and `cache.force_feature_computation=True`. After generating the cache, the training speed should dramatically increase. The bonus is that you only have to store the feature cache for the system you're training on, e.g. when using a cluster.

**Comment by ShawnCao2023** [comment]
Thank u @DanielDauner, it's true "After generating the cache, the training speed should dramatically increase". It takes about 1 day time to generate the cache, after that everything goes smoothly.
