### ISSUE TITLE
How to accelerate simulation process

### ISSUE THREAD

**Issue by dutjyf** [autonomousvision/tuplan_garage#35]
Dear Author:
I tried to run the simulation process and found it to be very slow and low CPU usage.I estimate it will take 30 days to run val14,so I'm asking if there's a way to speed up.

**Device Hardware**
- i7-12700K
- RTX3090 24G
- 64G RAM

**Comment by DanielDauner** [comment]
Hi @dutjyf, Thanks for your interest in our project! 

An evaluation time of 30 days sounds unreasonably long. Generally, the setting `worker=ray_distributed` is fastest since the scenario simulations are parallelized over logical cores (previously described in [Issue #11](https://github.com/autonomousvision/tuplan_garage/issues/11#issuecomment-1708733422)). The Val14 evaluation takes about 20-30 minutes on my local machine. Could you check your `worker` argument? For example, the argument `worker=sequential` is expected to be very slow.

I hope that helps!

**Comment by DanielDauner** [comment]
I am closing this issue for now. Feel free to re-open if you have further questions!
