### ISSUE TITLE
PDM-Hybrid that combined PDM-Closed with GC-PGP

### ISSUE THREAD

**Issue by dutjyf** [autonomousvision/tuplan_garage#36]
Dear Author
Thank you for your work.
I have built my own prediction models based on PGP and try to combine it with PDM-Closed, but It didn't work so well.
- CLS-R 61
- CLS-NR 60
- OLS 37

GC-PGP's feature is different from PDM
So I want to ask how to conbine GC-PGP with PDM-Closed.
Uploading the code would be great!
Thank you for all the help you've given me before!
wishes,
Yifan

**Comment by DanielDauner** [comment]
Hi @dutjyf,

Thanks for reaching out, but I'm having difficulty fully understanding your issue. You mention that you try to combine `PGP` (a motion forecasting model) into `PDM-Closed`. Would you like to improve the constant velocity forecast of `PDM-Closed`, or are you trying to merge the final trajectories like in `PDM-Hybrid`? If the latter is the case, it's unexpected that the CLS numbers are so low.

Using `GC-PGP` instead of `PDM-Offset` requires adapting the [planner class](https://github.com/autonomousvision/tuplan_garage/blob/main/tuplan_garage/planning/simulation/planner/pdm_planner/pdm_hybrid_planner.py) and [config](https://github.com/autonomousvision/tuplan_garage/blob/main/tuplan_garage/planning/script/config/simulation/planner/pdm_hybrid_planner.yaml) of PDM-Hybrid. I don't have code for it right away.

**Comment by dutjyf** [comment]
Thanks for your reply,I just want to merge the final trajectories like in `PDM-Hybrid`, but work not well.So I consider change the way to merge the final trajectories or rebuild prediction model.I try it again hahahaha :-)
