### ISSUE TITLE
Inconsistency between centerline and PDM-Closed trajectory

### ISSUE THREAD

**Issue by CristianGariboldi** [autonomousvision/tuplan_garage#37]
Hi, running the simulation I noticed that the centerline and the trajectory generated by PDM-Closed planner are not consistent in more than one scenario, as you can see in the pictures below (the red line is the centerline, the blue line is the PDM-Closed trajectory):
![plot](https://github.com/autonomousvision/tuplan_garage/assets/143978678/0cf164d6-c792-450d-b739-62ea01592aaa)
![plot1](https://github.com/autonomousvision/tuplan_garage/assets/143978678/0e95782f-9902-48db-85c2-fb7c293a0e8a)

My question is the following:

for the PDM-Open model you take as input just the centerline (together with ego history). Instead, for the hybrid model, you fuse together the PDM-Closed trajectory with the PDM-Open one (trained on the centerline).
Since, as shown in the plots above, PDM-Closed trajectory and centerline are not consistent, is it possible that this leads to a distorted hybrid trajectory?

![Screenshot from 2024-01-17 15-47-16](https://github.com/autonomousvision/tuplan_garage/assets/143978678/7af0535f-7d41-4f46-8b44-6b6ce3e7e98f)

Indeed, as shown above, the hybrid trajectory is distorted in the point where you fuse together PDM-Closed and PDM-Open.

Do you think this could be the cause of the distorted trajectory?
If that is the case, is there a reason why you trained the MLP-Open just taking the centerline as input?

Thanks a lot in advance!

**Comment by DanielDauner** [comment]
Hi @CristianGariboldi,

The trajectory proposals of `PDM-Closed` are a pairwise combination of [3 lateral centerline offsets](https://github.com/autonomousvision/tuplan_garage/blob/c00797bb7f21fd478c8fef05680a78b568bece07/tuplan_garage/planning/script/config/simulation/planner/pdm_closed_planner.yaml#L29) and [5 IDM policies](https://github.com/autonomousvision/tuplan_garage/blob/c00797bb7f21fd478c8fef05680a78b568bece07/tuplan_garage/planning/script/config/simulation/planner/pdm_closed_planner.yaml#L19C1-L27C67). For the centerline offsets we have ±1m and 0m. Therefore, it’s perfectly normal that the trajectory of `PDM-Closed` is not consistent with the centerline and runs parallel to the centerline (also see [here in code](https://github.com/autonomousvision/tuplan_garage/blob/c00797bb7f21fd478c8fef05680a78b568bece07/tuplan_garage/planning/simulation/planner/pdm_planner/abstract_pdm_closed_planner.py#L126C1-L132C67)). There might also be inconsistencies due to precision or interpolation errors, which should be negligible.

Note that `PDM-Hybrid` does use `PDM-Offset` for long-term correction. `PDM-Offset` follows the architecture and input of `PDM-Open` but additionally receives the output trajectory of `PDM-Closed` as input that includes the centerline offset (see [here in code](https://github.com/autonomousvision/tuplan_garage/blob/c00797bb7f21fd478c8fef05680a78b568bece07/tuplan_garage/planning/training/modeling/models/pdm_offset_model.py#L23C13-L23C13)). 

The `PDM-Hybrid` output often looks disturbed, especially if `PDM-Offset` is out-of-distribution during closed-loop simulation. Could you share the scenario token of the third image? I might have a look.

**Comment by CristianGariboldi** [comment]
@DanielDauner thanks for your quick reply! The scenario token is '1e77a04e93c75ba5', but in lots of cases you can notice a distortion in the fusion point of the 2 trajectories.
Since PDM-offset takes as input PDM-Closed trajectory together with the centerline, what could be the reason for this distortion?

**Comment by DanielDauner** [comment]
I checked the scenario. The distortion on the cutting point is nothing unusual. When `PDM-Offset` predicts large offsets to the `PDM-Closed` trajectory, the waypoints on the cutting point are far apart. The nuBoard connects the waypoints with a linear spline, making the output look distorted. 

Note that the concept of `PDM-Hybrid` purely serves to have a high OLS and CLS simultaneously. The underlying core for planning all comes from `PDM-Closed`.

I hope that helps. Let me know if you have further questions!

**Comment by CristianGariboldi** [comment]
@DanielDauner  thanks for your clarification! I'll close the issue.
