### ISSUE TITLE
calculate inference time

### ISSUE THREAD

**Issue by dutjyf** [autonomousvision/tuplan_garage#39]
Hello，
I see the eval table have **times** subject
I guess it is taken from `exp/simulation/runner_report.parquet`
but I don't know which it is from `duration`,`comput_trajectory_runtimes` and so on
so I want to ask how to calculate inference time(from `readme.md` table)
Thanks a lot!
![dfe78a81b36e736cbc18f5959aef658](https://github.com/autonomousvision/tuplan_garage/assets/102398709/d0c75575-034b-4ba6-afb5-9c7b36a0db43)

**Comment by DanielDauner** [comment]
Hi @dutjyf, we report the numbers of `compute_trajectory_runtimes_mean`. We ran the models with `worker=sequential` (as done in the nuPlan challenge) and enabled the GPU for ML-Planners (for `PDM-Open` note the fix in [Issue #38](https://github.com/autonomousvision/tuplan_garage/issues/38#issuecomment-1899962876)). We measured the runtime with an `AMD Ryzen 9 7950X` CPU and an `RTX 3090` GPU. Due to the long simulation in sequential mode, we only used 10 scenarios per challenge type. 

Thanks for pointing this out! We plan to add the smaller split to the repo soon with more details of the standardized benchmark.
 
Let me know if you have further questions!

**Comment by dutjyf** [comment]
I see.
Thanks for your reply!
I also have some advice to perfect this project.
- I advise build a small scenario config for test inference time
- GC-PGP have some metric like ADE FDE. So I want to have code to calculate them.
- add visualization code (of course nuboard can fix it,but It's not so well  
Please Author can consider them.
Thank you for your work to help me complete my dissertation！

**Comment by DanielDauner** [comment]
Thanks for your feedback! We are actively working on smaller scenario configs and an alternative visualization code. The latter may require a few more months. 

What exactly do you mean with ADE and FDE for GC-PGP? Do you require the final metrics after model training? Note that we have minADE and minFDE implemented (see [`prediction_metrics.py`](https://github.com/autonomousvision/tuplan_garage/blob/main/tuplan_garage/planning/training/modeling/metrics/prediction_metrics.py)) for model training.
