### ISSUE TITLE
time for training

### ISSUE THREAD

**Issue by gujiamitu** [autonomousvision/tuplan_garage#40]
Hello，
Great work 
How much time needed for training based on a single 3090 GPU
Thanks a lot!

**Comment by DanielDauner** [comment]
Hi @Sabrinashurong 

Thanks for your interest in our project!

That depends on the model. `PDM-Open` or `PDM-Offset` take about 30 min to train (as described in Issue [#13](https://github.com/autonomousvision/tuplan_garage/issues/13#issuecomment-1704750452) and [#11](https://github.com/autonomousvision/tuplan_garage/issues/11#issuecomment-1691584188)). Before training, you should cache the train150k dataset (as described [here](https://github.com/autonomousvision/tuplan_garage/issues/13#issuecomment-1704750452)). Caching can take a while (depending on your CPU count) because `PDM-Closed` is run on each training sample. 

Let me know if you have further questions!
